# NumPy || Numric Python

!["NumPy"](https://miro.medium.com/v2/resize:fit:1400/0*SpprfEyaZaWE_Pez)

In [1]:
import numpy as np

In [2]:
# 1D Array 
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
# 2D Array 
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [8,9,10]
    ])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [5]:
arr.shape

(3, 3)

In [6]:
arr[0].mean()

2.0

In [7]:
arr[0].max()

3

In [8]:
arr = np.zeros([5,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.ones([5,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.linspace(1,100,500)
arr

array([  1.        ,   1.19839679,   1.39679359,   1.59519038,
         1.79358717,   1.99198397,   2.19038076,   2.38877756,
         2.58717435,   2.78557114,   2.98396794,   3.18236473,
         3.38076152,   3.57915832,   3.77755511,   3.9759519 ,
         4.1743487 ,   4.37274549,   4.57114228,   4.76953908,
         4.96793587,   5.16633267,   5.36472946,   5.56312625,
         5.76152305,   5.95991984,   6.15831663,   6.35671343,
         6.55511022,   6.75350701,   6.95190381,   7.1503006 ,
         7.34869739,   7.54709419,   7.74549098,   7.94388778,
         8.14228457,   8.34068136,   8.53907816,   8.73747495,
         8.93587174,   9.13426854,   9.33266533,   9.53106212,
         9.72945892,   9.92785571,  10.12625251,  10.3246493 ,
        10.52304609,  10.72144289,  10.91983968,  11.11823647,
        11.31663327,  11.51503006,  11.71342685,  11.91182365,
        12.11022044,  12.30861723,  12.50701403,  12.70541082,
        12.90380762,  13.10220441,  13.3006012 ,  13.49

In [11]:
arr = np.ones([10,10])
arr.reshape(5,20)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [12]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [13]:
# Changes In Copy Will Not Effect on Original Array
arr = np.array(['apple', 'banana', 'cherry'])
x = arr.copy()
x[0] = "Grape"
arr


array(['apple', 'banana', 'cherry'], dtype='<U6')

In [14]:
# Changes In View Will Effect on Original Array
arr = np.array(['apple', 'banana', 'cherry'])
x = arr.view()
x[0] = "Grape"
arr

array(['Grape', 'banana', 'cherry'], dtype='<U6')

In [15]:
arr = np.array(['apple', 'banana', 'cherry'])
for item in arr:
    print(item)

apple
banana
cherry


In [16]:
# Printing The 2d Array:
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [8,9,10]
    ])

for i in range(len(arr)):
    for j in  range(len(arr[i])):
        print(arr[i][j], end= " | ")
    print()


1 | 2 | 3 | 
4 | 5 | 6 | 
8 | 9 | 10 | 


In [17]:
#! 3d List:
N = [
    [
        [1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]
    ],
    [
        [1, 20, 3], 
        [4, 5, 6], 
        [7, 8, 9]
    ],
    [
        [1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]
    ]
]

arr = np.array(N)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1, 20,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [18]:
for i in range(len(arr)):
    print("-----------")
    for j in range(len(arr[i])):
        for k in range(len(arr[i][j])):
            print(arr[i][j][k], end= " | ")
        print()
print("-----------")

-----------
1 | 2 | 3 | 
4 | 5 | 6 | 
7 | 8 | 9 | 
-----------
1 | 20 | 3 | 
4 | 5 | 6 | 
7 | 8 | 9 | 
-----------
1 | 2 | 3 | 
4 | 5 | 6 | 
7 | 8 | 9 | 
-----------


In [19]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [21]:
x = [1,2,3,4,5,6,7,8]
y = [9,10,11,12,13,14,15,16]

z = x+y
z = x.extend(z)
# Both are Same 
z

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [30]:
x = np.array([1,2,3,])
y = np.array([9,10,11])

# z = x+y # This Will Calculate the Sum Of Arrays
# z = np.add(x,y) # This Will Calculate the Sum Of Arrays
z = np.concatenate((x,y)) 
z

array([ 1,  2,  3,  9, 10, 11])

In [35]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis = 0)
arr = np.concatenate((arr1, arr2), axis = 1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [45]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [54]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
# x = np.searchsorted(arr, 7, side='right')

print(x)

1


In [55]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [56]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [59]:
arr = np.array([41, 42, 43, 44,44,33,22,11,44,55,66,7,8,9,10])

# x = [True, False, True, False]
x = []
for i in arr:
    if i % 3 == 0:
        x.append(True)
    else:
        x.append(False)

newarr = arr[x]

print(newarr)

[42 33 66  9]


In [64]:
from numpy import random
x = random.randint(10,22)  # Given Range

print(x)

17


In [71]:
x = random.rand() # 0 - 1

print(x)

65.72442403441022


In [76]:

x=random.randint(100, size=(5))
x=random.randint(20,100, size=(5,4))
print(x)

[[87 64 74 55]
 [38 42 31 82]
 [71 99 50 75]
 [46 53 48 46]
 [32 85 25 87]]


In [78]:

x = random.rand(5,6)

print(x)

[[0.52697564 0.65291543 0.85071792 0.69675964 0.66948717 0.98789151]
 [0.78829428 0.36624011 0.47742264 0.64984638 0.88449909 0.7750973 ]
 [0.58033397 0.45505861 0.97728186 0.73920869 0.6424355  0.58133166]
 [0.01454369 0.41312637 0.45383962 0.69872905 0.47763239 0.93149926]
 [0.72221202 0.45069744 0.5268339  0.35592111 0.16864209 0.63799473]]


In [83]:
arr = np.array([3, 5, 7, 9])
x = random.choice(arr)
x

array([[7, 7, 3, 9, 9],
       [5, 9, 5, 9, 5],
       [9, 9, 9, 9, 7]])

In [85]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
x

array([[9, 5, 7, 5, 9],
       [7, 5, 7, 3, 7],
       [9, 3, 7, 7, 5]])

In [86]:
x = random.normal(size=(2, 3))
x

array([[-1.35178727, -1.40219772, -0.53640024],
       [-0.33274077,  0.2415874 , -2.55813792]])

In [88]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)
x

12

In [89]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)
x

3